"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { Icon } from "@/components/icons";
import type { SaveGoalInput, SavingsGoal } from "@/lib/goals";
import { formatMoney, formatMoneyInput, parseMoneyInput } from "@/lib/money";

export function GoalDialog({ open, goal, today, onClose, onSave }: { open: boolean; goal: SavingsGoal | null; today: string; onClose: () => void; onSave: (input: SaveGoalInput) => Promise<{ ok: boolean; message?: string }> }) {
  const ref = useRef<HTMLDialogElement>(null); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) dialog.showModal(); if (!open && dialog.open) dialog.close(); }, [open]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const target = parseMoneyInput(String(data.get("target") ?? "")); const deadline = String(data.get("deadline") ?? "") || null; const input = { id: goal?.id, name: String(data.get("name") ?? "").trim(), target, deadline }; if (!input.name) { setError("Nhập tên mục tiêu."); return; } if (!Number.isSafeInteger(target) || target <= 0) { setError("Số tiền mục tiêu cần lớn hơn 0."); return; } if (target < (goal?.allocated ?? 0)) { setError("Mức đích không thể thấp hơn tiền đã dành."); return; } setSubmitting(true); let result: { ok: boolean; message?: string }; try { result = await onSave(input); } catch { result = { ok: false, message: "Mất kết nối khi lưu mục tiêu." }; } finally { setSubmitting(false); } if (!result.ok) { setError(result.message || "Không thể lưu mục tiêu."); return; } setError(""); }
  return <dialog ref={ref} className="account-dialog goal-dialog" onCancel={(event) => { event.preventDefault(); if (!submitting) onClose(); }} aria-labelledby="goal-dialog-title"><div className="dialog-heading"><div><p className="eyebrow">Kế hoạch tương lai</p><h2 id="goal-dialog-title">{goal ? "Sửa mục tiêu" : "Thêm mục tiêu"}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={submitting} aria-label="Đóng"><Icon name="close" /></button></div><form className="account-form" onSubmit={submit}><label><span>Tên mục tiêu</span><input name="name" maxLength={80} defaultValue={goal?.name ?? ""} placeholder="Ví dụ: Quỹ khẩn cấp" autoFocus /></label><label><span>Số tiền muốn đạt</span><div className="account-money-input"><input name="target" inputMode="decimal" defaultValue={goal ? formatMoneyInput(String(goal.target)) : ""} placeholder="0" onInput={(event) => { event.currentTarget.value = formatMoneyInput(event.currentTarget.value); setError(""); }} /><strong>₫</strong></div></label><label><span>Ngày muốn hoàn thành <small>(không bắt buộc)</small></span><input name="deadline" type="date" min={goal?.deadline && goal.deadline < today ? goal.deadline : today} defaultValue={goal?.deadline ?? ""} /></label><p className="account-form-hint">MoneyFlow dùng thời hạn để tính số nên dành mỗi ngày. Bạn vẫn có thể thay đổi sau.</p>{error && <p className="field-error" role="alert">{error}</p>}<div className="dialog-footer-actions"><button className="secondary-button" type="button" onClick={onClose} disabled={submitting}>Hủy</button><button className="primary-button account-submit" type="submit" disabled={submitting}><Icon name="check" />{submitting ? "Đang lưu..." : "Lưu mục tiêu"}</button></div></form></dialog>;
}

export function GoalAllocationDialog({ open, goal, mode, onClose, onSubmit }: { open: boolean; goal: SavingsGoal | null; mode: "allocate" | "release"; onClose: () => void; onSubmit: (amount: number) => Promise<{ ok: boolean; message?: string }> }) {
  const ref = useRef<HTMLDialogElement>(null); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) dialog.showModal(); if (!open && dialog.open) dialog.close(); }, [open]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const amount = parseMoneyInput(String(new FormData(event.currentTarget).get("amount") ?? "")); const max = mode === "allocate" ? Math.max(0, (goal?.target ?? 0) - (goal?.allocated ?? 0)) : goal?.allocated ?? 0; if (!Number.isSafeInteger(amount) || amount <= 0) { setError("Số tiền cần lớn hơn 0."); return; } if (amount > max) { setError(mode === "allocate" ? "Số tiền vượt phần còn thiếu của mục tiêu." : "Không thể rút quá số tiền đã dành."); return; } setSubmitting(true); let result: { ok: boolean; message?: string }; try { result = await onSubmit(amount); } catch { result = { ok: false, message: "Mất kết nối khi điều chỉnh." }; } finally { setSubmitting(false); } if (!result.ok) { setError(result.message || "Không thể điều chỉnh mục tiêu."); return; } setError(""); }
  const max = mode === "allocate" ? Math.max(0, (goal?.target ?? 0) - (goal?.allocated ?? 0)) : goal?.allocated ?? 0;
  return <dialog ref={ref} className="account-dialog goal-allocation-dialog" onCancel={(event) => { event.preventDefault(); if (!submitting) onClose(); }} aria-labelledby="allocation-dialog-title"><div className="dialog-heading"><div><p className="eyebrow">{mode === "allocate" ? "Khóa theo kế hoạch" : "Mở khóa tiền"}</p><h2 id="allocation-dialog-title">{mode === "allocate" ? "Dành thêm tiền" : "Rút khỏi mục tiêu"}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={submitting} aria-label="Đóng"><Icon name="close" /></button></div><div className="goal-allocation-context"><span className="round-icon purple"><Icon name={mode === "allocate" ? "lock" : "restore"} /></span><div><strong>{goal?.name}</strong><p>{mode === "allocate" ? `Còn thiếu ${formatMoney(max)}` : `Đang dành ${formatMoney(max)}`}</p></div></div><form className="account-form" onSubmit={submit}><label><span>Số tiền</span><div className="account-money-input"><input name="amount" inputMode="decimal" placeholder="0" onInput={(event) => { event.currentTarget.value = formatMoneyInput(event.currentTarget.value); setError(""); }} autoFocus /><strong>₫</strong></div></label><p className="account-form-hint">{mode === "allocate" ? "Đây không phải khoản chi. Tổng tài sản không đổi, nhưng tiền sẽ được loại khỏi số có thể chi." : "Tiền được mở khóa và quay lại phần có thể chi; tổng tài sản vẫn không đổi."}</p>{error && <p className="field-error" role="alert">{error}</p>}<div className="dialog-footer-actions"><button className="secondary-button" type="button" onClick={onClose} disabled={submitting}>Hủy</button><button className="primary-button account-submit" type="submit" disabled={submitting || max === 0}><Icon name={mode === "allocate" ? "lock" : "restore"} />{submitting ? "Đang cập nhật..." : mode === "allocate" ? "Dành tiền" : "Rút tiền"}</button></div></form></dialog>;
}
