"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { Icon } from "@/components/icons";
import { formatMoneyInput, parseMoneyInput } from "@/lib/money";
import type { AccountOption, CreateTransferInput } from "@/lib/sample-data";

export function TransferDialog({ open, accounts, onClose, onTransfer }: { open: boolean; accounts: AccountOption[]; onClose: () => void; onTransfer: (input: CreateTransferInput) => Promise<{ ok: boolean; message?: string }> }) {
  const ref = useRef<HTMLDialogElement>(null); const idempotencyRef = useRef<string | null>(null);
  const [sourceId, setSourceId] = useState(accounts[0]?.id ?? ""); const [destinationId, setDestinationId] = useState(accounts[1]?.id ?? ""); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) dialog.showModal(); if (!open && dialog.open) dialog.close(); }, [open]);
  const source = accounts.some((item) => item.id === sourceId) ? sourceId : accounts[0]?.id ?? "";
  const destinationOptions = accounts.filter((item) => item.id !== source); const destination = destinationOptions.some((item) => item.id === destinationId) ? destinationId : destinationOptions[0]?.id ?? "";
  function changed() { idempotencyRef.current = null; setError(""); }
  function swap() { if (!source || !destination) return; setSourceId(destination); setDestinationId(source); changed(); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const parsedAmount = parseMoneyInput(amount); if (!Number.isSafeInteger(parsedAmount) || parsedAmount <= 0) { setError("Nhập số tiền lớn hơn 0."); return; } if (!source || !destination || source === destination) { setError("Chọn hai tài khoản khác nhau."); return; } const idempotencyKey = idempotencyRef.current ?? crypto.randomUUID(); idempotencyRef.current = idempotencyKey; const occurredOn = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); setSubmitting(true); let result: { ok: boolean; message?: string }; try { result = await onTransfer({ sourceAccountId: source, destinationAccountId: destination, amount: parsedAmount, note: note.trim(), occurredOn, idempotencyKey }); } catch { result = { ok: false, message: "Mất kết nối khi chuyển tiền." }; } finally { setSubmitting(false); } if (!result.ok) { setError(result.message || "Không thể chuyển tiền."); return; } idempotencyRef.current = null; setAmount(""); setNote(""); setError(""); }
  return <dialog ref={ref} className="transaction-dialog transfer-dialog" onCancel={(event) => { event.preventDefault(); if (!submitting) onClose(); }} aria-labelledby="transfer-dialog-title"><div className="dialog-handle" aria-hidden="true" /><div className="dialog-heading"><div><p className="eyebrow">Giữa các ví của bạn</p><h2 id="transfer-dialog-title">Chuyển tiền</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={submitting} aria-label="Đóng"><Icon name="close" /></button></div><form onSubmit={submit}><label className="amount-field"><span>Số tiền chuyển</span><div><input autoFocus inputMode="numeric" autoComplete="off" placeholder="0" value={amount} onChange={(event) => { setAmount(formatMoneyInput(event.target.value)); changed(); }} /><strong>₫</strong></div></label>{error && <p className="field-error" role="alert">{error}</p>}<div className="transfer-accounts"><label><span>Từ tài khoản</span><select value={source} onChange={(event) => { setSourceId(event.target.value); changed(); }}>{accounts.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><button type="button" onClick={swap} className="transfer-swap" aria-label="Đổi chiều chuyển tiền"><Icon name="arrows" /></button><label><span>Đến tài khoản</span><select value={destination} onChange={(event) => { setDestinationId(event.target.value); changed(); }}>{destinationOptions.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><label className="transfer-note"><span>Ghi chú</span><input value={note} onChange={(event) => { setNote(event.target.value); changed(); }} placeholder="Ví dụ: Chuyển sang quỹ tiết kiệm" maxLength={500} /></label><div className="transfer-explainer"><Icon name="check" /><p><strong>Tổng tài sản không đổi.</strong> MoneyFlow trừ tài khoản nguồn và cộng tài khoản đích trong cùng một giao dịch.</p></div><button className="primary-button dialog-submit" type="submit" disabled={submitting || accounts.length < 2}><Icon name="arrows" />{submitting ? "Đang chuyển..." : "Xác nhận chuyển tiền"}</button></form></dialog>;
}
